# Generated by Django 2.0.7 on 2018-07-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180721_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('librarian', 'student'),)},
        ),
    ]
